### Get all cookbooks
GET http://localhost:3000/cookbook
###

### Get a cookbook by user id
GET http://localhost:3000/cookbook/1
###

### Create a cookbook by user id
POST http://localhost:3000/cookbook/5
Content-Type: application/json

{
    "title": "My first cookbook",
    "description": "This is my first cookbook",
    "isFavorite": false,
    "isPublic": true
}
###

### Add a recipe to a cookbook
PUT http://localhost:3000/cookbook/8
Content-Type: application/json

{
    "cookbookId": 1,
    "recipeId": 1
 }